services:
  github-wiki-skeleton:
    build: 
      context: .
      dockerfile: .env-files/Dockerfile.github
    ports:
     - "8080:8080"
     - "35729:35729"
    environment: 
     - BUNDLE_GEMFILE=.env-files/Gemfile.github
    volumes:
     - .:/srv/jekyll
     - github_site:/srv/jekyll/_site
    command: bundle exec jekyll serve --host 127.0.0.1 --force_polling --livereload --trace  --port 8080
volumes: 
  github_site:

